"""post, department tables add

Revision ID: 4e6315420dc1
Revises: eb3ffeef00a6
Create Date: 2023-10-27 17:23:09.593506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6315420dc1'
down_revision: Union[str, None] = 'eb3ffeef00a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)


    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.add_column('staff', sa.Column('fk_department_id', sa.Integer(), nullable=False))
    op.add_column('staff', sa.Column('fk_post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'staff', 'department', ['fk_department_id'], ['id'])
    op.create_foreign_key(None, 'staff', 'post', ['fk_post_id'], ['id'])
    op.drop_column('staff', 'department')
    op.drop_column('staff', 'post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('post', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('staff', sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'fk_post_id')
    op.drop_column('staff', 'fk_department_id')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
